name: Test commit
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test_commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/previous-releases
        node-version: [ 16.x, 18.x, 20.x, 21.x ]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
      - run: npm start
